# Generated by Django 5.1.1 on 2024-10-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
