# Generated by Django 5.1.1 on 2024-12-06 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishrating',
            name='summary',
        ),
        migrations.AddField(
            model_name='dishratingsummary',
            name='dish',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='food.dish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dishrating',
            name='dish',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.dish'),
        ),
    ]
