# Generated by Django 5.1.1 on 2024-10-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
