# Generated by Django 5.1.1 on 2024-12-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishchosen',
            old_name='chosen',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='dishhistory',
            old_name='history',
            new_name='dish',
        ),
    ]
