# Generated by Django 5.1.1 on 2024-12-13 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishfavourite',
            name='dish',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='food.dish'),
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='dish',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='food.dish'),
        ),
    ]
