# Generated by Django 5.1.1 on 2024-12-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_chosen_dishchosen_dish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('breakfast', 'завтрак'), ('dinner', 'обед'), ('dinner', 'ужин')], default='breakfast', max_length=16),
        ),
    ]
