# Generated by Django 5.1.1 on 2024-12-13 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_dishfavourite_dish_alter_dishhistory_dish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dishhistory',
            constraint=models.UniqueConstraint(fields=('user', 'dish'), name='uniq_history'),
        ),
    ]
