# Generated by Django 5.1.1 on 2024-12-06 15:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_remove_dishrating_summary_dishratingsummary_dish_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dishrating',
            name='unique_user_dish',
        ),
        migrations.AddConstraint(
            model_name='dishrating',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user'),
        ),
    ]
