# Generated by Django 5.1.1 on 2024-12-06 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_remove_dishrating_unique_user_dish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishrating',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.dish'),
        ),
    ]
