# Generated by Django 5.1.1 on 2024-12-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_dishrating_dish'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dishrating',
            name='unique_user',
        ),
    ]
