# Generated by Django 5.1.1 on 2024-12-14 16:58

from django.db import migrations

import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("food", "Ingredient")
    for row in MyModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_ingredient_uuid'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
