# Generated by Django 5.1.1 on 2024-12-11 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_dish_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DishFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dishchosen',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='dishchosen',
            name='user',
        ),
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.CharField(choices=[('breakfast', 'завтрак'), ('lunch', 'обед'), ('dinner', 'ужин')], default='breakfast', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='dishrating',
            constraint=models.UniqueConstraint(fields=('user', 'dish'), name='uniq_user_dish'),
        ),
        migrations.AddField(
            model_name='dishfavourite',
            name='dish',
            field=models.ManyToManyField(related_name='favourite', to='food.dish'),
        ),
        migrations.AddField(
            model_name='dishfavourite',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DishChosen',
        ),
    ]
