# Generated by Django 5.1.1 on 2024-10-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_ingredient_delete_product_alter_dish_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='product',
            new_name='ingredient',
        ),
    ]
