# Generated by Django 5.1.1 on 2024-12-14 17:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20241214_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
