# Generated by Django 5.1.1 on 2024-10-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rename_product_dish_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
