# Generated by Django 5.1.1 on 2024-12-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_dish_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'завтрак'), (2, 'обед'), (3, 'ужин')], db_index=True, default=1),
        ),
    ]
