# Generated by Django 5.1.1 on 2024-12-11 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_dish_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishfavourite',
            name='dish',
        ),
        migrations.AlterField(
            model_name='dishfavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='dishhistory',
            name='dish',
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dishfavourite',
            name='dish',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='food.dish'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dishhistory',
            name='dish',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='food.dish'),
            preserve_default=False,
        ),
    ]
