# Generated by Django 5.1.1 on 2024-12-06 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_dishchosen_dishhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishhistory',
            name='history',
        ),
        migrations.RemoveField(
            model_name='dishhistory',
            name='user',
        ),
        migrations.DeleteModel(
            name='DishChosen',
        ),
        migrations.DeleteModel(
            name='DishHistory',
        ),
    ]
