# Generated by Django 5.1.1 on 2024-12-16 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_uniq_uuid_dish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dishfavourite',
            constraint=models.UniqueConstraint(fields=('user', 'dish'), name='uniq_favourite'),
        ),
    ]
