# Generated by Django 5.1.1 on 2024-12-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_dishchosen_dishhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishchosen',
            name='chosen',
        ),
        migrations.RemoveField(
            model_name='dishhistory',
            name='history',
        ),
        migrations.AddField(
            model_name='dish',
            name='chosen',
            field=models.ManyToManyField(related_name='chosen', to='food.dishchosen'),
        ),
        migrations.AddField(
            model_name='dish',
            name='history',
            field=models.ManyToManyField(related_name='history', to='food.dishhistory'),
        ),
    ]
