# Generated by Django 5.1.1 on 2024-12-06 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_remove_dishchosen_chosen_remove_dishhistory_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='chosen',
        ),
        migrations.RemoveField(
            model_name='dishhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='history',
        ),
        migrations.DeleteModel(
            name='DishChosen',
        ),
        migrations.DeleteModel(
            name='DishHistory',
        ),
    ]
