# Generated by Django 5.1.1 on 2024-12-16 10:33
import uuid

from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    model_list = ['DishRating', 'DishRatingSummary', 'DishHistory', 'DishFavourite']
    for model in model_list:
        food_model = apps.get_model('food', model)
        food_model.objects.update(uuid=uuid.uuid4())



class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_dishfavourite_uuid_dishhistory_uuid_dishrating_uuid_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
