# Generated by Django 5.1.1 on 2024-12-16 10:34
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_gen_uuid_dish_history_favourite_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishfavourite',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='dishhistory',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='dishrating',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='dishratingsummary',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
