# Generated by Django 5.1.1 on 2024-12-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('food', '0014_allergen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allergens', to='children.child'),
        ),
    ]
