# Generated by Django 5.1.1 on 2024-12-16 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_alter_allergen_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='user',
            new_name='child',
        ),
    ]
