# Generated by Django 5.1.1 on 2024-12-20 16:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0016_rename_user_allergen_child"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allergen",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, serialize=False, unique=True),
        ),
    ]
