# Generated by Django 5.1.1 on 2024-12-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0017_add_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergen",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
