# Generated by Django 5.1.1 on 2024-12-20 17:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0018_auto_20241220_1703"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allergen",
            name="name",
        ),
        migrations.AlterField(
            model_name="allergen",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
