# Generated by Django 5.1.1 on 2024-12-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0019_remove_allergen_name_alter_allergen_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="allergen",
            name="ingredient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="food.ingredient",
            ),
            preserve_default=False,
        ),
    ]
