# Generated by Django 5.1.1 on 2024-12-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("children", "0001_initial"),
        ("food", "0020_allergen_ingredient"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="allergen",
            constraint=models.UniqueConstraint(
                fields=("ingredient", "child"), name="uniq_ingredient_child"
            ),
        ),
    ]
